version: '3.9'
services:
  webapp:
    build:
      args:
        - PIP_VERSION=${WEBAPP_PIP_VERSION:-23.0.1}
        - POETRY_VERSION=${WEBAPP_POETRY_VERSION:-1.3.2}
        - PYTHON_VERSION=${WEBAPP_PYTHON_VERSION:-3.10.10}
        - VERSION=${WEBAPP_VERSION:-dev}
      context: services/webapp/
    container_name: webapp.m-pt1-63-23
    depends_on:
      - db
    entrypoint: [ task, run-server-prod ]
    environment:
      DATABASE_URL: postgresql://m-pt1-63-23:m-pt1-63-23@db:5432/m-pt1-63-23
      MODE_DEBUG: 1
      PORT: 80
      TEST_SERVICE_URL: http://webapp:80
    image: webapp.m-pt1-63-23:${WEBAPP_VERSION:-dev}
    networks:
      - m-pt1-63-23
    ports:
      - "8000:80"
    tmpfs:
      - /app/.local/:mode=777,size=10m,uid=1000,gid=1000
    volumes:
      - ./services/webapp/:/app/:ro
  db:
    build:
      context: services/db/
      args:
        - VERSION=${DB_VERSION:-dev}
    container_name: db.m-pt1-63-23
    environment:
      POSTGRES_USER: m-pt1-63-23
      POSTGRES_PASSWORD: m-pt1-63-23
      POSTGRES_DB: m-pt1-63-23
    image: db.m-pt1-63-23:${DB_VERSION:-dev}
    ports:
      - "5432:5432"
    networks:
      - m-pt1-63-23
    volumes:
      - ./.local/services/db/data/:/var/lib/postgresql/data:rw
  dba:
    build:
      context: services/dba/
    container_name: dba.m-pt1-63-23
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    image: dba.m-pt1-63-23:dev
    ports:
      - "8801:80"
    networks:
      - m-pt1-63-23
  docs:
    build:
      args:
        - PIP_VERSION=${DOCS_PIP_VERSION:-23.0.1}
        - POETRY_VERSION=${DOCS_POETRY_VERSION:-1.3.2}
        - PYTHON_VERSION=${DOCS_PYTHON_VERSION:-3.10.10}
        - VERSION=${WEBAPP_VERSION:-dev}
      context: services/docs/
    container_name: docs.m-pt1-63-23
    entrypoint: [ task, run-server-dev ]
    image: docs.m-pt1-63-23:${DOCS_VERSION:-dev}
    networks:
      - m-pt1-63-23
    ports:
      - "8802:8000"
    volumes:
      - ./services/docs/:/docs/:rw
networks:
  m-pt1-63-23:
    name: m-pt1-63-23.net
    driver: bridge
