site_name: 'M-PT1-63-23'
site_url: 'https://alexander-sidorov.github.io/m-pt1-63-23'
repo_url: 'https://github.com/alexander-sidorov/m-pt1-63-23'
site_author: 'M-PT1-63-23'

dev_addr: '0.0.0.0:8000'
site_dir: '.local/mkdocs/site/'

nav:
  - 'About': 'index.md'

theme:
  name: 'material'
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: yellow
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - 'navigation.instant'
    - 'navigation.sections'
    - 'navigation.tabs'
    - 'navigation.tracking'
